###
# Get a list of fieldsDTO
GET http://localhost:3000/fields/

###
# Create a new field
POST http://localhost:3000/fields
Content-Type : Application/json

{
    "name" : "Marw",
    "location" : "Bruxelles"
}

###
# Get a field with his id 
GET http://localhost:3000/fields/1

###
# Update a field
PUT http://localhost:3000/fields/999
Content-Type: application/json

{
    "id": 999,
    "name": "Skrrrrrr",
    "location": "StJosse"

}