###
# GEt list of gameShortDtO
GET http://localhost:3000/games

###
# Create a new game
POST http://localhost:3000/games/
Content-Type: application/json

{
    "name": "po vs lice",
    "homeTeamId": 2,
    "awayTeamId":1
}

###
# Get a game with his id 
GET http://localhost:3000/games/3/

###
# update a game with his id 
PUT http://localhost:3000/games/3
Content-Type: application/json

{
    "id": 3,
    "name" : "FC MMMM vs FC SSSSSS",
    "status" : "created",
    "homeTeamId": 2,
    "awayTeamId": 1,
    "homeScore": 0,
    "awayScore": 0,
    "scheduledDate": "2026-06-11T14:00:00.000Z",
    "fieldId": 1
}

###
# update a game with his id 
PUT http://localhost:3000/games/5
Content-Type: application/json

{
    "id": 5,
    "name" : "ra vo ro",
    "status" : "created",
    "homeTeamId": 2,
    "awayTeamId": 1,
    "scheduledDate": "2027-06-15T14:00:00.000Z",
    "fieldId": 1
}

###
# DELETE A GAME WITH HIS ID
DELETE http://localhost:3000/games/3

###
# Update the score of a team in a game 
PATCH http://localhost:3000/games/3/score/4/4

###
# Update the status of a game 
PATCH http://localhost:3000/games/7/status/cancelled


###
# Update the status of a game 
PATCH http://localhost:3000/games/4/status/created

  
