
###
# Test requirements of teams routes
# Assumes that create_users.http, create_teams.http and create_fields.http have been run before.
#

@server = http://127.0.0.1:3000
@adminuser = admin
@adminpassword = admin
@playeruser = player
@playerpassword = player
@refuser = ref
@refpassword = ref
@traineruser = trainer
@trainerpassword = trainer
@known_date = 2026-09-18

###
## Login as admin
# @name admin_login
POST {{server}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "{{adminuser}}",
  "password": "{{adminpassword}}"
}

###
## Login as player
# @name player_login
POST {{server}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "{{playeruser}}",
  "password": "{{playerpassword}}"
}

###
## Login as trainer
# @name trainer_login
POST {{server}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "{{traineruser}}",
  "password": "{{trainerpassword}}"
}

###
## Login as referee
# @name ref_login
POST {{server}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "{{refuser}}",
  "password": "{{refpassword}}"
}

###
# A referee can post a new game with empty body
#
POST {{server}}/games HTTP/1.1
Content-Type: application/json
Authorization: {{ref_login.response.body.token}}

{}

###
# A referee can post a new game with information in it
#
POST {{server}}/games HTTP/1.1
Content-Type: application/json
Authorization: {{ref_login.response.body.token}}

{
  "name": "Best game of the year",
  "scheduledDate": "2026-09-03"
}

###
# An admin cannot post a new game
#
POST {{server}}/games HTTP/1.1
Content-Type: application/json
Authorization: {{admin_login.response.body.token}}

{}

###
# Add game in the past
POST {{server}}/games HTTP/1.1
Content-Type: application/json
Authorization: {{ref_login.response.body.token}}

{
  "name": "Some old game",
  "scheduledDate": "2021-03-18"
}

###
# Everyone can get basic informations about all current and future games
#
GET {{server}}/games HTTP/1.1

###
# Everyone? can get information about a specific game
GET {{server}}/games/1

###
# Referees can update games
#
PUT {{server}}/games/1
Content-Type: application/json
Authorization: {{ref_login.response.body.token}}

{
  "id": 1,
  "status": "created"
}

###
# If fieldId and dates are set, status is SCHEDULED
#
PUT {{server}}/games/1
Content-Type: application/json
Authorization: {{ref_login.response.body.token}}

{
  "id": 1,
  "status": "created",
  "fieldId": 1,
  "scheduledDate": "{{known_date}}"
}

###
# Field cannot be booked twice
#
PUT {{server}}/games/2
Content-Type: application/json
Authorization: {{ref_login.response.body.token}}

{
  "id": 2,
  "status": "created",
  "fieldId": 1,
  "scheduledDate": "{{known_date}}"
}
###
# Non-admins cannot hard delete a game
#
DELETE {{server}}/games/1
Authorization: {{ref_login.response.body.token}}

###
# Admin can hard delete a game
#
DELETE {{server}}/games/1
Authorization: {{admin_login.response.body.token}}


###
# Player cannot change game status
#
PATCH {{server}}/games/2/status/scheduled
Authorization: {{player_login.response.body.token}}

###
# Referee can change game status if transition rules are respected
#
PATCH {{server}}/games/2/status/cancelled
Authorization: {{ref_login.response.body.token}}

###
# Referee cannot change game status if transition rules are not respected
#
PATCH {{server}}/games/2/status/created
Authorization: {{ref_login.response.body.token}}

###
# Create a game, schedule it, start it, update score, finish it:
# @name game
POST {{server}}/games HTTP/1.1
Content-Type: application/json
Authorization: {{ref_login.response.body.token}}

{
  "name": "Best game of the year",
  "scheduledDate": "2026-09-03"
}
###
# Should set the game as scheduled.
PUT {{server}}/games/{{game.response.body.id}}
Content-Type: application/json
Authorization: {{ref_login.response.body.token}}

{
  "id": {{game.response.body.id}},
  "status": "created",
  "name": "{{game.response.body.name}}",
  "scheduledDate": "{{game.response.body.scheduledDate}}",
  "homeTeamId": 1,
  "awayTeamId": 3,
  "fieldId": 1
}
###
# Start the game
PATCH {{server}}/games/{{game.response.body.id}}/status/started
Authorization: {{ref_login.response.body.token}}
###
# Update the score
PATCH {{server}}/games/{{game.response.body.id}}/score/1/0
Authorization: {{ref_login.response.body.token}}
###
# Update the score
PATCH {{server}}/games/{{game.response.body.id}}/score/1/2
Authorization: {{ref_login.response.body.token}}
###
# Started games shouldn't be able to change teams
PUT {{server}}/games/{{game.response.body.id}}
Content-Type: application/json
Authorization: {{ref_login.response.body.token}}

{
  "id": {{game.response.body.id}},
  "status": "started",
  "name": "{{game.response.body.name}}",
  "scheduledDate": "{{game.response.body.scheduledDate}}",
  "homeTeamId": 3,
  "awayTeamId": 1,
  "fieldId": 1
}
###
# Finish the game
PATCH {{server}}/games/{{game.response.body.id}}/status/finished
Authorization: {{ref_login.response.body.token}}
###
# We should no longer be able to update the score
PATCH {{server}}/games/{{game.response.body.id}}/score/2/2
Authorization: {{ref_login.response.body.token}}
###
# We should no longer be able to update the status
PATCH {{server}}/games/{{game.response.body.id}}/status/started
Authorization: {{ref_login.response.body.token}}